In [2]:
import pandas
item_info=pandas.read_csv('1234.csv')
print(type(item_info))
print(item_info.dtypes)
print(help(pandas.read_csv))

<class 'pandas.core.frame.DataFrame'>
code       object
name       object
iqc_id    float64
name.1     object
dtype: object
Help on function read_csv in module pandas.io.parsers:

read_csv(filepath_or_buffer, sep=',', delimiter=None, header='infer', names=None, index_col=None, usecols=None, squeeze=False, prefix=None, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, iterator=False, chunksize=None, compression='infer', thousands=None, decimal=b'.', lineterminator=None, quotechar='"', quoting=0, escapechar=None, comment=None, encoding=None, dialect=None, tupleize_cols=None, error_bad_lines=True, warn_bad_lines=True, skipfooter=0, doublequote=True, delim_whitespace=False, low_memory=True, memory_map=False, float_precision=None)
    Read CSV (comma-separated) file into DataFrame

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the `online docs for IO Tools
    <http://pandas.pydata.org/pandas-docs/stable/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, pathlib.Path, py._path.local.LocalPath or any \
    object with a read() method (such as a file handle or StringIO)
        The string could be a URL. Valid URL schemes include http, ftp, s3, and
        file. For file URLs, a host is expected. For instance, a local file could
        be file://localhost/path/to/table.csv
    sep : str, default ','
        Delimiter to use. If sep is None, the C engine cannot automatically detect
        the separator, but the Python parsing engine can, meaning the latter will
        be used and automatically detect the separator by Python's builtin sniffer
        tool, ``csv.Sniffer``. In addition, separators longer than 1 character and
        different from ``'\s+'`` will be interpreted as regular expressions and
        will also force the use of the Python parsing engine. Note that regex
        delimiters are prone to ignoring quoted data. Regex example: ``'\r\t'``
    delimiter : str, default ``None``
        Alternative argument name for sep.
    delim_whitespace : boolean, default False
        Specifies whether or not whitespace (e.g. ``' '`` or ``'\t'``) will be
        used as the sep. Equivalent to setting ``sep='\s+'``. If this option
        is set to True, nothing should be passed in for the ``delimiter``
        parameter.

        .. versionadded:: 0.18.1 support for the Python parser.

    header : int or list of ints, default 'infer'
        Row number(s) to use as the column names, and the start of the
        data.  Default behavior is to infer the column names: if no names
        are passed the behavior is identical to ``header=0`` and column
        names are inferred from the first line of the file, if column
        names are passed explicitly then the behavior is identical to
        ``header=None``. Explicitly pass ``header=0`` to be able to
        replace existing names. The header can be a list of integers that
        specify row locations for a multi-index on the columns
        e.g. [0,1,3]. Intervening rows that are not specified will be
        skipped (e.g. 2 in this example is skipped). Note that this
        parameter ignores commented lines and empty lines if
        ``skip_blank_lines=True``, so header=0 denotes the first line of
        data rather than the first line of the file.
    names : array-like, default None
        List of column names to use. If file contains no header row, then you
        should explicitly pass header=None. Duplicates in this list will cause
        a ``UserWarning`` to be issued.
    index_col : int or sequence or False, default None
        Column to use as the row labels of the DataFrame. If a sequence is given, a
        MultiIndex is used. If you have a malformed file with delimiters at the end
        of each line, you might consider index_col=False to force pandas to _not_
        use the first column as the index (row names)
    usecols : list-like or callable, default None
        Return a subset of the columns. If list-like, all elements must either
        be positional (i.e. integer indices into the document columns) or strings
        that correspond to column names provided either by the user in `names` or
        inferred from the document header row(s). For example, a valid list-like
        `usecols` parameter would be [0, 1, 2] or ['foo', 'bar', 'baz']. Element
        order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
        To instantiate a DataFrame from ``data`` with element order preserved use
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]`` for columns
        in ``['foo', 'bar']`` order or
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
        for ``['bar', 'foo']`` order.

        If callable, the callable function will be evaluated against the column
        names, returning names where the callable function evaluates to True. An
        example of a valid callable argument would be ``lambda x: x.upper() in
        ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
        parsing time and lower memory usage.
    squeeze : boolean, default False
        If the parsed data only contains one column then return a Series
    prefix : str, default None
        Prefix to add to column numbers when no header, e.g. 'X' for X0, X1, ...
    mangle_dupe_cols : boolean, default True
        Duplicate columns will be specified as 'X', 'X.1', ...'X.N', rather than
        'X'...'X'. Passing in False will cause data to be overwritten if there
        are duplicate names in the columns.
    dtype : Type name or dict of column -> type, default None
        Data type for data or columns. E.g. {'a': np.float64, 'b': np.int32}
        Use `str` or `object` together with suitable `na_values` settings
        to preserve and not interpret dtype.
        If converters are specified, they will be applied INSTEAD
        of dtype conversion.
    engine : {'c', 'python'}, optional
        Parser engine to use. The C engine is faster while the python engine is
        currently more feature-complete.
    converters : dict, default None
        Dict of functions for converting values in certain columns. Keys can either
        be integers or column labels
    true_values : list, default None
        Values to consider as True
    false_values : list, default None
        Values to consider as False
    skipinitialspace : boolean, default False
        Skip spaces after delimiter.
    skiprows : list-like or integer or callable, default None
        Line numbers to skip (0-indexed) or number of lines to skip (int)
        at the start of the file.

        If callable, the callable function will be evaluated against the row
        indices, returning True if the row should be skipped and False otherwise.
        An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
    skipfooter : int, default 0
        Number of lines at bottom of file to skip (Unsupported with engine='c')
    nrows : int, default None
        Number of rows of file to read. Useful for reading pieces of large files
    na_values : scalar, str, list-like, or dict, default None
        Additional strings to recognize as NA/NaN. If dict passed, specific
        per-column NA values.  By default the following values are interpreted as
        NaN: '', '#N/A', '#N/A N/A', '#NA', '-1.#IND', '-1.#QNAN', '-NaN', '-nan',
        '1.#IND', '1.#QNAN', 'N/A', 'NA', 'NULL', 'NaN', 'n/a', 'nan',
        'null'.
    keep_default_na : bool, default True
        Whether or not to include the default NaN values when parsing the data.
        Depending on whether `na_values` is passed in, the behavior is as follows:

        * If `keep_default_na` is True, and `na_values` are specified, `na_values`
          is appended to the default NaN values used for parsing.
        * If `keep_default_na` is True, and `na_values` are not specified, only
          the default NaN values are used for parsing.
        * If `keep_default_na` is False, and `na_values` are specified, only
          the NaN values specified `na_values` are used for parsing.
        * If `keep_default_na` is False, and `na_values` are not specified, no
          strings will be parsed as NaN.

        Note that if `na_filter` is passed in as False, the `keep_default_na` and
        `na_values` parameters will be ignored.
    na_filter : boolean, default True
        Detect missing value markers (empty strings and the value of na_values). In
        data without any NAs, passing na_filter=False can improve the performance
        of reading a large file
    verbose : boolean, default False
        Indicate number of NA values placed in non-numeric columns
    skip_blank_lines : boolean, default True
        If True, skip over blank lines rather than interpreting as NaN values
    parse_dates : boolean or list of ints or names or list of lists or dict, default False

        * boolean. If True -> try parsing the index.
        * list of ints or names. e.g. If [1, 2, 3] -> try parsing columns 1, 2, 3
          each as a separate date column.
        * list of lists. e.g.  If [[1, 3]] -> combine columns 1 and 3 and parse as
          a single date column.
        * dict, e.g. {'foo' : [1, 3]} -> parse columns 1, 3 as date and call result
          'foo'

        If a column or index contains an unparseable date, the entire column or
        index will be returned unaltered as an object data type. For non-standard
        datetime parsing, use ``pd.to_datetime`` after ``pd.read_csv``

        Note: A fast-path exists for iso8601-formatted dates.
    infer_datetime_format : boolean, default False
        If True and `parse_dates` is enabled, pandas will attempt to infer the
        format of the datetime strings in the columns, and if it can be inferred,
        switch to a faster method of parsing them. In some cases this can increase
        the parsing speed by 5-10x.
    keep_date_col : boolean, default False
        If True and `parse_dates` specifies combining multiple columns then
        keep the original columns.
    date_parser : function, default None
        Function to use for converting a sequence of string columns to an array of
        datetime instances. The default uses ``dateutil.parser.parser`` to do the
        conversion. Pandas will try to call `date_parser` in three different ways,
        advancing to the next if an exception occurs: 1) Pass one or more arrays
        (as defined by `parse_dates`) as arguments; 2) concatenate (row-wise) the
        string values from the columns defined by `parse_dates` into a single array
        and pass that; and 3) call `date_parser` once for each row using one or
        more strings (corresponding to the columns defined by `parse_dates`) as
        arguments.
    dayfirst : boolean, default False
        DD/MM format dates, international and European format
    iterator : boolean, default False
        Return TextFileReader object for iteration or getting chunks with
        ``get_chunk()``.
    chunksize : int, default None
        Return TextFileReader object for iteration.
        See the `IO Tools docs
        <http://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
        for more information on ``iterator`` and ``chunksize``.
    compression : {'infer', 'gzip', 'bz2', 'zip', 'xz', None}, default 'infer'
        For on-the-fly decompression of on-disk data. If 'infer' and
        `filepath_or_buffer` is path-like, then detect compression from the
        following extensions: '.gz', '.bz2', '.zip', or '.xz' (otherwise no
        decompression). If using 'zip', the ZIP file must contain only one data
        file to be read in. Set to None for no decompression.

        .. versionadded:: 0.18.1 support for 'zip' and 'xz' compression.

    thousands : str, default None
        Thousands separator
    decimal : str, default '.'
        Character to recognize as decimal point (e.g. use ',' for European data).
    float_precision : string, default None
        Specifies which converter the C engine should use for floating-point
        values. The options are `None` for the ordinary converter,
        `high` for the high-precision converter, and `round_trip` for the
        round-trip converter.
    lineterminator : str (length 1), default None
        Character to break file into lines. Only valid with C parser.
    quotechar : str (length 1), optional
        The character used to denote the start and end of a quoted item. Quoted
        items can include the delimiter and it will be ignored.
    quoting : int or csv.QUOTE_* instance, default 0
        Control field quoting behavior per ``csv.QUOTE_*`` constants. Use one of
        QUOTE_MINIMAL (0), QUOTE_ALL (1), QUOTE_NONNUMERIC (2) or QUOTE_NONE (3).
    doublequote : boolean, default ``True``
       When quotechar is specified and quoting is not ``QUOTE_NONE``, indicate
       whether or not to interpret two consecutive quotechar elements INSIDE a
       field as a single ``quotechar`` element.
    escapechar : str (length 1), default None
        One-character string used to escape delimiter when quoting is QUOTE_NONE.
    comment : str, default None
        Indicates remainder of line should not be parsed. If found at the beginning
        of a line, the line will be ignored altogether. This parameter must be a
        single character. Like empty lines (as long as ``skip_blank_lines=True``),
        fully commented lines are ignored by the parameter `header` but not by
        `skiprows`. For example, if ``comment='#'``, parsing
        ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in 'a,b,c' being
        treated as the header.
    encoding : str, default None
        Encoding to use for UTF when reading/writing (ex. 'utf-8'). `List of Python
        standard encodings
        <https://docs.python.org/3/library/codecs.html#standard-encodings>`_
    dialect : str or csv.Dialect instance, default None
        If provided, this parameter will override values (default or not) for the
        following parameters: `delimiter`, `doublequote`, `escapechar`,
        `skipinitialspace`, `quotechar`, and `quoting`. If it is necessary to
        override values, a ParserWarning will be issued. See csv.Dialect
        documentation for more details.
    tupleize_cols : boolean, default False
        .. deprecated:: 0.21.0
           This argument will be removed and will always convert to MultiIndex

        Leave a list of tuples on columns as is (default is to convert to
        a MultiIndex on the columns)
    error_bad_lines : boolean, default True
        Lines with too many fields (e.g. a csv line with too many commas) will by
        default cause an exception to be raised, and no DataFrame will be returned.
        If False, then these "bad lines" will dropped from the DataFrame that is
        returned.
    warn_bad_lines : boolean, default True
        If error_bad_lines is False, and warn_bad_lines is True, a warning for each
        "bad line" will be output.
    low_memory : boolean, default True
        Internally process the file in chunks, resulting in lower memory use
        while parsing, but possibly mixed type inference.  To ensure no mixed
        types either set False, or specify the type with the `dtype` parameter.
        Note that the entire file is read into a single DataFrame regardless,
        use the `chunksize` or `iterator` parameter to return the data in chunks.
        (Only valid with C parser)
    memory_map : boolean, default False
        If a filepath is provided for `filepath_or_buffer`, map the file object
        directly onto memory and access the data directly from there. Using this
        option can improve performance because there is no longer any I/O overhead.

    Returns
    -------
    result : DataFrame or TextParser

None

In [10]:
print(item_info.head())
print(item_info.tail(3))  #倒数三行

print(item_info.shape)

item_info.columns

            code                  name  iqc_id name.1
0  1..05.021.003             停用-排水阀套筒新  4091.0     黄萍
1   1.01.001.001         方陶瓷/宝路YB001-方  4091.0     黄萍
2   1.01.001.002         圆陶瓷/宝路YB002-圆  4091.0     黄萍
3   1.01.001.003  圆陶瓷/美加华YM002-M 300孔距  4091.0     黄萍
4   1.01.001.004  圆陶瓷/美加华YM002-L 400孔距  4091.0     黄萍
           code                                            name  iqc_id name.1
7229  1.13.0015                                不干胶/两联/PET/25*15     NaN    NaN
7230  1.13.0016                              伊奈水箱不干胶/银灰标签/40*15     NaN    NaN
7231  1.13.0017  其它/海德精机精抛白皮HD-F06-610/&Oslash;610* &Oslash;160     NaN    NaN
(7232, 4)

Index(['code', 'name', 'iqc_id', 'name.1'], dtype='object')

In [13]:
print(item_info.loc[0])  #第几行取值

code      1..05.021.003
name          停用-排水阀套筒新
iqc_id             4091
name.1               黄萍
Name: 0, dtype: object

In [14]:
item_info.loc[3:6]

           code                   name  iqc_id name.1
3  1.01.001.003   圆陶瓷/美加华YM002-M 300孔距  4091.0     黄萍
4  1.01.001.004   圆陶瓷/美加华YM002-L 400孔距  4091.0     黄萍
5  1.01.001.005  YG陶瓷 300无孔/惠达YH005-M1  4091.0     黄萍
6  1.01.001.006  YG陶瓷 300有孔/惠达YH005-M2  4091.0     黄萍

In [20]:
item_info.loc[[2,5,10]]

            code                   name  iqc_id name.1
2   1.01.001.002          圆陶瓷/宝路YB002-圆  4091.0     黄萍
5   1.01.001.005  YG陶瓷 300无孔/惠达YH005-M1  4091.0     黄萍
10  1.01.001.010          陶瓷/YT陶瓷/400有孔  4091.0     黄萍

In [21]:
two_five_ten=[2,5,10]
item_info.loc[two_five_ten]

            code                   name  iqc_id name.1
2   1.01.001.002          圆陶瓷/宝路YB002-圆  4091.0     黄萍
5   1.01.001.005  YG陶瓷 300无孔/惠达YH005-M1  4091.0     黄萍
10  1.01.001.010          陶瓷/YT陶瓷/400有孔  4091.0     黄萍

In [23]:
ndb_col=item_info['code']
print(ndb_col)

0       1..05.021.003
1        1.01.001.001
2        1.01.001.002
3        1.01.001.003
4        1.01.001.004
5        1.01.001.005
6        1.01.001.006
7        1.01.001.007
8        1.01.001.008
9        1.01.001.009
10       1.01.001.010
11       1.01.001.011
12       1.01.001.012
13       1.01.001.013
14       1.01.001.017
15       1.01.001.018
16       1.01.001.019
17       1.01.001.020
18       1.01.001.021
19       1.01.001.022
20       1.01.001.023
21       1.01.001.024
22       1.01.001.025
23       1.01.001.026
24       1.01.001.027
25       1.01.001.028
26       1.01.001.029
27       1.01.001.030
28       1.01.001.031
29       1.01.001.032
            ...
7202     1.10.033.022
7203     1.10.033.023
7204     1.10.033.024
7205     1.10.033.025
7206     1.10.033.026
7207     1.10.033.027
7208     1.10.033.028
7209      1.10.16.003
7210         1.11.001
7211         1.11.002
7212         1.11.003
7213         1.11.004
7214         1.11.005
7215         1.11.006
7216        1.13.0002
7217        1.13.0003
7218        1.13.0004
7219        1.13.0005
7220        1.13.0006
7221        1.13.0007
7222        1.13.0008
7223        1.13.0009
7224        1.13.0010
7225        1.13.0011
7226        1.13.0012
7227        1.13.0013
7228        1.13.0014
7229        1.13.0015
7230        1.13.0016
7231        1.13.0017
Name: code, Length: 7232, dtype: object

In [24]:
colums = ['name','code']
print(item_info[colums])

                                                name           code
0                                          停用-排水阀套筒新  1..05.021.003
1                                      方陶瓷/宝路YB001-方   1.01.001.001
2                                      圆陶瓷/宝路YB002-圆   1.01.001.002
3                               圆陶瓷/美加华YM002-M 300孔距   1.01.001.003
4                               圆陶瓷/美加华YM002-L 400孔距   1.01.001.004
5                              YG陶瓷 300无孔/惠达YH005-M1   1.01.001.005
6                              YG陶瓷 300有孔/惠达YH005-M2   1.01.001.006
7                              YG陶瓷 400无孔/惠达YH005-L1   1.01.001.007
8                              YG陶瓷 400有孔/惠达YH005-L2   1.01.001.008
9                                      陶瓷/YT陶瓷/300有孔   1.01.001.009
10                                     陶瓷/YT陶瓷/400有孔   1.01.001.010
11                                     陶瓷/YT陶瓷/300无孔   1.01.001.011
12                                     陶瓷/YT陶瓷/400无孔   1.01.001.012
13                                               NaN   1.01.001.013
14                                     立维陶瓷/300有孔/YT   1.01.001.017
15                                     立维陶瓷/300无孔/YT   1.01.001.018
16                                     立维陶瓷/400有孔/YT   1.01.001.019
17                                     立维陶瓷/400无孔/YT   1.01.001.020
18                                     立维陶瓷/300有孔/YG   1.01.001.021
19                                     立维陶瓷/300无孔/YG   1.01.001.022
20                                     立维陶瓷/400有孔/YG   1.01.001.023
21                                     立维陶瓷/400无孔/YG   1.01.001.024
22                                   陶瓷/YG美规陶瓷/300无孔   1.01.001.025
23                                 陶瓷/YG美规陶瓷装置/300有孔   1.01.001.026
24                                   陶瓷/YG美规陶瓷/300有孔   1.01.001.027
25                                新乐陶瓷/300有孔/YG/CD59   1.01.001.028
26                               新乐陶瓷/300无孔/YG/CD59S   1.01.001.029
27                                新乐陶瓷/400有孔/YG/CB59   1.01.001.030
28                               新乐陶瓷/400无孔/YG/CB59S   1.01.001.031
29                                    陶瓷/零水压陶瓷/300无孔   1.01.001.032
...                                              ...            ...
7202                                       加热器灌胶组装治具   1.10.033.022
7203                                       安全阀密封测试治具   1.10.033.023
7204                                       流量计密封测试治具   1.10.033.024
7205                                 清洗器钢管锁螺钉治具（1托6）   1.10.033.025
7206                                   分配阀锁电机治具（1托8）   1.10.033.026
7207                                       清洗器喷头固定治具   1.10.033.027
7208                                             工装板   1.10.033.028
7209                                             电子秤    1.10.16.003
7210                                         塑料(ABS)       1.11.001
7211                                         塑料(ABS)       1.11.002
7212                                             PP料       1.11.003
7213                                         塑料(ABS)       1.11.004
7214                                             POM       1.11.005
7215                                             PPS       1.11.006
7216                          其它/漏保上壳体(智米专用）/PC K-30      1.13.0002
7217                          其它/漏保下壳体(智米专用）/PC K-30      1.13.0003
7218                             其它/内盖（智米专用）/PC K-30      1.13.0004
7219                           其它/复位按钮(智米专用）/PC K-30      1.13.0005
7220                           其它/试验按钮(智米专用）/PC K-30      1.13.0006
7221                           其它/灯片(智米专用）/透明PC K-30      1.13.0007
7222                                其它/螺孔塞(智米专用）/TPE      1.13.0008
7223                              其它/提手(智米专用)/PP亚光透明      1.13.0009
7224                            其它/提手底座(智米专用)/PP亚光透明      1.13.0010
7225                                        其它/除臭块/       1.13.0011
7226                                    其它/不干胶/40*30      1.13.0012
7227                                其它/不干胶/PET/35*10      1.13.0013
7228                                 其它/碳带/树脂/40*300      1.13.0014
7229                                不干胶/两联/PET/25*15      1.13.0015
7230                              伊奈水箱不干胶/银灰标签/40*15      1.13.0016
7231  其它/海德精机精抛白皮HD-F06-610/&Oslash;610* &Oslash;160      1.13.0017

[7232 rows x 2 columns]

In [25]:
col_names=item_info.columns.tolist()
print(col_names)

['code', 'name', 'iqc_id', 'name.1']

In [58]:
#item_info['code']=item_info['code'].astype(str)
new_item=item_info['code'].apply(lambda x: x.replace('.',''))  #去掉 ’ .‘ 操作
print(item_info.shape)
item_info['new_item']=new_item
item_info.head(3)
#print(item_info.shape)

(7232, 5)

            code           name  iqc_id name.1   new_item
0  1..05.021.003      停用-排水阀套筒新  4091.0     黄萍  105021003
1   1.01.001.001  方陶瓷/宝路YB001-方  4091.0     黄萍  101001001
2   1.01.001.002  圆陶瓷/宝路YB002-圆  4091.0     黄萍  101001002

In [61]:
#排序
item_info.sort_values('new_item',inplace=True)
print(item_info['new_item'])
item_info.sort_values('new_item',inplace=True,ascending=False)
print(item_info['new_item'])

1       101001001
2       101001002
3       101001003
4       101001004
5       101001005
6       101001006
7       101001007
8       101001008
9       101001009
10      101001010
11      101001011
12      101001012
13      101001013
14      101001017
15      101001018
16      101001019
17      101001020
18      101001021
19      101001022
20      101001023
21      101001024
22      101001025
23      101001026
24      101001027
25      101001028
26      101001029
27      101001030
28      101001031
29      101001032
30      101001033
          ...
7202    110033022
7203    110033023
7204    110033024
7205    110033025
7206    110033026
7207    110033027
7208    110033028
7209     11016003
7210       111001
7211       111002
7212       111003
7213       111004
7214       111005
7215       111006
7216      1130002
7217      1130003
7218      1130004
7219      1130005
7220      1130006
7221      1130007
7222      1130008
7223      1130009
7224      1130010
7225      1130011
7226      1130012
7227      1130013
7228      1130014
7229      1130015
7230      1130016
7231      1130017
Name: new_item, Length: 7232, dtype: object
7231      1130017
7230      1130016
7229      1130015
7228      1130014
7227      1130013
7226      1130012
7225      1130011
7224      1130010
7223      1130009
7222      1130008
7221      1130007
7220      1130006
7219      1130005
7218      1130004
7217      1130003
7216      1130002
7215       111006
7214       111005
7213       111004
7212       111003
7211       111002
7210       111001
7209     11016003
7208    110033028
7207    110033027
7206    110033026
7205    110033025
7204    110033024
7203    110033023
7202    110033022
          ...
30      101001033
29      101001032
28      101001031
27      101001030
26      101001029
25      101001028
24      101001027
23      101001026
22      101001025
21      101001024
20      101001023
19      101001022
18      101001021
17      101001020
16      101001019
15      101001018
14      101001017
13      101001013
12      101001012
11      101001011
10      101001010
9       101001009
8       101001008
7       101001007
6       101001006
5       101001005
4       101001004
3       101001003
2       101001002
1       101001001
Name: new_item, Length: 7232, dtype: object